[package]
name = "tinysort"
version = "0.1.0"
authors = ["CensoredUsername <cens.username@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[profile.release]
debug = true